[package]
name = "fox"
version = "0.1.0"
authors = ["Vijay Jayaram <vijay.jayaram2@gmail.com>"]

[lib]
name = "fox"
path = "src/fox/message.rs"

[dependencies]
clap = "2.24.2"
serde = "1.0.7"
serde_derive = "1.0.7"
serde_json = "1.0.2"

